#!/bin/bash
# Run script for {skill_name}
# Generated by rust-skill-creator

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BINARY="$SCRIPT_DIR/../rust/target/release/{skill_name}"

if [ ! -f "$BINARY" ]; then
    echo "Error: Binary not found at $BINARY"
    echo "Run build.sh first to compile the application."
    exit 1
fi

exec "$BINARY" "$@"
