#!/bin/bash
# Build script for {skill_name}
# Generated by rust-skill-creator

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
RUST_DIR="$SCRIPT_DIR/../rust"

echo "Building {skill_name}..."
cd "$RUST_DIR"

cargo build --release

if [ $? -eq 0 ]; then
    echo "Build successful!"
    echo "Binary: $RUST_DIR/target/release/{skill_name}"
else
    echo "Build failed!"
    exit 1
fi
